CXX = g++
CXXFLAGS = -std=c++11
GTKFLAGS = `/usr/bin/pkg-config gtkmm-3.0 --cflags --libs`

all: executable

executable:  jdo3643_main.o jdo3643_Book.o jdo3643_Book_Window.o jdo3643_Bundle.o jdo3643_Check_In_Window.o jdo3643_Customer.o jdo3643_Customer_Window.o jdo3643_Controller.o jdo3643_Date.o jdo3643_Librarian.o jdo3643_Librarian_Window.o jdo3643_Library.o jdo3643_Main_Window.o jdo3643_Media.o jdo3643_Movie.o jdo3643_Movie_Window.o jdo3643_Music_Album.o jdo3643_Music_Album_Window.o jdo3643_Payment_Window.o jdo3643_Television_Show_Season.o jdo3643_Television_Show_Season_Window.o jdo3643_Transaction.o jdo3643_Video_Game.o jdo3643_Video_Game_Window.o jdo3643_View.o
	$(CXX)	$(CXXFLAGS) jdo3643_main.o jdo3643_Book.o jdo3643_Book_Window.o jdo3643_Bundle.o jdo3643_Check_In_Window.o jdo3643_Customer.o jdo3643_Customer_Window.o jdo3643_Controller.o jdo3643_Date.o  jdo3643_Librarian.o jdo3643_Librarian_Window.o jdo3643_Library.o jdo3643_Main_Window.o jdo3643_Media.o jdo3643_Movie.o jdo3643_Movie_Window.o jdo3643_Payment_Window.o jdo3643_Music_Album.o jdo3643_Music_Album_Window.o jdo3643_Television_Show_Season.o jdo3643_Television_Show_Season_Window.o jdo3643_Transaction.o jdo3643_Video_Game.o jdo3643_Video_Game_Window.o jdo3643_View.o $(GTKFLAGS)

jdo3643_main.o: jdo3643_main.cpp jdo3643_Book.cpp jdo3643_Book_Window.cpp jdo3643_Bundle.cpp jdo3643_Check_In_Window.o jdo3643_Customer.cpp jdo3643_Customer_Window.cpp jdo3643_Controller.cpp jdo3643_Date.cpp  jdo3643_Librarian.cpp jdo3643_Librarian_Window.cpp jdo3643_Library.cpp jdo3643_Main_Window.cpp jdo3643_Media.cpp jdo3643_Movie.cpp jdo3643_Movie_Window.cpp jdo3643_Music_Album.cpp jdo3643_Music_Album_Window.cpp jdo3643_Payment_Window.cpp jdo3643_Television_Show_Season.cpp jdo3643_Television_Show_Season_Window.cpp jdo3643_Transaction.cpp jdo3643_Video_Game.cpp jdo3643_Video_Game_Window.cpp jdo3643_View.cpp
	$(CXX)	$(CXXFLAGS)	-c jdo3643_main.cpp $(GTKFLAGS)

jdo3643_Book.o: jdo3643_Book.h jdo3643_Book.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Book.cpp $(GTKFLAGS)

jdo3643_Book_Window.o: jdo3643_Book_Window.h jdo3643_Book_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Book_Window.cpp $(GTKFLAGS)

jdo3643_Bundle.o: jdo3643_Bundle.h jdo3643_Bundle.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Bundle.cpp $(GTKFLAGS)

jdo3643_Check_In_Window.o: jdo3643_Check_In_Window.h jdo3643_Check_In_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Check_In_Window.cpp $(GTKFLAGS)

jdo3643_Customer.o: jdo3643_Customer.h jdo3643_Customer.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Customer.cpp $(GTKFLAGS)

jdo3643_Customer_Window.o: jdo3643_Customer_Window.h jdo3643_Customer_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Customer_Window.cpp $(GTKFLAGS)

jdo3643_Controller.o: jdo3643_Controller.h jdo3643_Controller.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Controller.cpp $(GTKFLAGS)

jdo3643_Date.o: jdo3643_Date.h jdo3643_Date.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Date.cpp $(GTKFLAGS)
	
jdo3643_Librarian.o: jdo3643_Librarian.h jdo3643_Librarian.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Librarian.cpp $(GTKFLAGS)

jdo3643_Librarian_Window.o: jdo3643_Librarian_Window.h jdo3643_Librarian_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Librarian_Window.cpp $(GTKFLAGS)

jdo3643_Library.o: jdo3643_Library.h jdo3643_Library.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Library.cpp $(GTKFLAGS)

jdo3643_Main_Window.o: jdo3643_Main_Window.h jdo3643_Main_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Main_Window.cpp $(GTKFLAGS)

jdo3643_Media.o: jdo3643_Media.h jdo3643_Media.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Media.cpp $(GTKFLAGS)

jdo3643_Movie.o: jdo3643_Movie.h jdo3643_Movie.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Movie.cpp $(GTKFLAGS)

jdo3643_Movie_Window.o: jdo3643_Movie_Window.h jdo3643_Movie_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Movie_Window.cpp $(GTKFLAGS)

jdo3643_Music_Album.o: jdo3643_Music_Album.h jdo3643_Music_Album.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Music_Album.cpp $(GTKFLAGS)

jdo3643_Music_Album_Window.o: jdo3643_Music_Album_Window.h jdo3643_Music_Album_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Music_Album_Window.cpp $(GTKFLAGS)

jdo3643_Payment_Window.o: jdo3643_Payment_Window.h jdo3643_Payment_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Payment_Window.cpp $(GTKFLAGS)

jdo3643_Television_Show_Season.o: jdo3643_Television_Show_Season.h jdo3643_Television_Show_Season.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Television_Show_Season.cpp $(GTKFLAGS)

jdo3643_Television_Show_Season_Window.o: jdo3643_Television_Show_Season_Window.h jdo3643_Television_Show_Season_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Television_Show_Season_Window.cpp $(GTKFLAGS)

jdo3643_Transaction.o: jdo3643_Transaction.h jdo3643_Transaction.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Transaction.cpp $(GTKFLAGS)

jdo3643_Video_Game.o: jdo3643_Video_Game.h jdo3643_Video_Game.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Video_Game.cpp $(GTKFLAGS)

jdo3643_Video_Game_Window.o: jdo3643_Video_Game_Window.h jdo3643_Video_Game_Window.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_Video_Game_Window.cpp $(GTKFLAGS)

jdo3643_View.o: jdo3643_View.h jdo3643_View.cpp
	$(CXX) $(CXXFLAGS) -c jdo3643_View.cpp $(GTKFLAGS)

clean:
	rm -f *.o a.out
