local L = LibStub("AceLocale-3.0"):NewLocale("GLT", "enUS", true)
L["General"] = true
L["General Options"] = true
L["Guild Loot Tracker"] = true
L["Guild Loot Tracker Options"] = true
L["Colour"] = true
L["Colour and Accessibility Options"] = true
L["Title Colour"] = true
L["Picks a Custom Colour for the Mod Names."] = true
L["Author Colour"] = true
L["Picks a Custom Colour for the Author."] = true
L["Command Colour"] = true
L["Picks a Custom Colour for the Commands."] = true
L["Emphasis Colour"] = true
L["Picks a Custom Colour for emphasis."] = true
L["Normal Colour"] = true
L["Picks a Custom Colour to be used normally."] = true
L["Editor Colours"] = true
L["Spell Colour"] = true
L["Picks a Custom Colour to be used for Spells and Abilities."] = true
L["Unknown Colour"] = true
L["Picks a Custom Colour to be used for unknown terms."] = true
L["Icon Colour"] = true
L["Picks a Custom Colour to be used for Icons."] = true
L["SpecID/ClassID Colour"] = true
L["Picks a Custom Colour to be used for numbers."] = true
L["String Colour"] = true
L["Picks a Custom Colour to be used for strings."] = true
L["Conditionals Colour"] = true
L["Picks a Custom Colour to be used for macro conditionals eg [mod:shift]"] = true
L["Help Colour"] = true
L["Picks a Custom Colour to be used for braces and indents."] = true
L["Step Functions"] = true
L["Picks a Custom Colour to be used for StepFunctions."] = true
L["Language Colour"] = true
L["Picks a Custom Colour to be used for language descriptors"] = true
L["Blizzard Functions Colour"] = true
L["Picks a Custom Colour to be used for Macro Keywords like /cast and /target"] = true
L["About"] = true
L["About Guild Loot Tracker"] = true
L["History"] = true
L["Guild Loot Tracker was written to track loot over multiple raid groups by TimothyLuke."] = true
L["Supporters"] = true
L["The following people donate monthly via Patreon for the ongoing maintenance and development of Guild Loot Tracker.  Their support is greatly appreciated."] = true
L["Debug"] = true
L["Debug Mode Options"] = true
L["Enable Mod Debug Mode"] = true
L["This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"] = true
L["Debug Output Options"] = true
L["Display debug messages in Chat Window"] = true
L["This will display debug messages in the Chat window."] = true
L["Grey"] = true
L["White"] = true
L['Green'] = true
L["Blue"] = true
L["Epic"] = true
L["Legendary"] = true
L["Loot Threshold"] = true
L["Minimum item quality to log."] = true

L["Guild Loot Tracker is out of date. You can download the newest version from"] = true
L["Enable Debug for the following Modules"] = true
L["This will display debug messages for the "] = true
--
